[phases.setup]
nixPkgs = ['nodejs', 'npm', 'yarn']


[phases.install]
cmds = [
  'cd pruebaFront && npm install'  
]

[phases.build]
cmds = [
  'cd pruebaFront && npm run build'  
]

[start]
cmd = 'java -jar demo/target/demo-0.0.1-SNAPSHOT.jar' 
